# 转发端：负责将接收转发请求并将请求结果返回给接收端
api:
  # 转发端配置
  forwarder:
    # 是否启用该接转发端，默认为 false
    # 在 false 的情况下，下面的配置全部不生效
    enable: true
    # 允许请求的接收端
    # 只允许在白名单的接收端的请求
    receiver:
      - id: 9e706b500c85 # 接收端 ID
        security-key: a2e3ca51d8666e0c0409b # 接收端预共享密钥